# Configuration file for the AdminLTE bundle
#
# For more information about the bundle settings visit:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/configurations.md
#
# For tabs in the control_sidebar (right screen) add the 'control_sidebar' config key:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/control_sidebar.md

admin_lte:
    options:
        skin: skin-black
        fixed_layout: false
        boxed_layout: false
        collapsed_sidebar: false
        mini_sidebar: true

    knp_menu:
        enable: false

    routes:
        adminlte_welcome: admin
        adminlte_profile: profile
        adminlte_login: fos_user_security_login
        adminlte_login_check: fos_user_security_check
        adminlte_registration: fos_user_registration_register
        adminlte_password_reset: fos_user_resetting_request
        adminlte_message: message
        adminlte_messages: messages
        adminlte_notification: notification
        adminlte_notifications: notifications
        adminlte_task: task
        adminlte_tasks: tasks

    theme:
        widget:
            type: 'primary'
            bordered: true
            collapsible: false
            collapsible_title: 'Collapse'
            removable: false
            removable_title: 'Remove'
            solid: false
            use_footer: true
        button:
            type: 'primary'
            size: false